export const metadata = { title: 'Privacy Policy — GSSO', description: 'GSSO data protection and privacy policy.' };

export default function PrivacyPage() {
  return (
    <div className="min-h-screen" style={{ fontFamily: "'Libre Franklin', sans-serif", background: '#faf9f6', color: '#3a3a3a' }}>
      <nav className="sticky top-0 z-50 bg-white border-b border-[#d5d0c8]"><div className="max-w-[860px] mx-auto px-8 py-3 flex justify-between items-center"><a href="/" className="flex items-center gap-3"><svg width="36" height="36" viewBox="0 0 44 44" fill="none"><circle cx="22" cy="22" r="20" stroke="#0c1220" strokeWidth="1.5"/><ellipse cx="22" cy="22" rx="12" ry="20" stroke="#0c1220" strokeWidth="1" transform="rotate(25 22 22)"/><circle cx="22" cy="22" r="2.5" fill="#b91c1c"/></svg><div><strong className="font-serif text-base text-[#1a1a1a]">Geo-Strategic Studies</strong></div></a><a href="/" className="text-[13px] text-[#3a3a3a] hover:text-[#b91c1c]">&larr; Back</a></div></nav>
      <div className="max-w-[860px] mx-auto px-8 py-16">
        <h1 className="font-serif text-4xl font-bold text-[#1a1a1a] mb-2">Privacy Policy</h1>
        <p className="text-[#6b6b6b] text-sm mb-12">Last updated: April 2026</p>
        <div className="prose max-w-none text-[15px] text-[#3a3a3a] leading-relaxed space-y-8">
          <section><h2 className="font-serif text-2xl font-bold text-[#1a1a1a] border-b-2 border-[#1a1a1a] pb-2">1. Data Controller</h2><p className="mt-4">Geo-Strategic Studies Organisation (&ldquo;GSSO,&rdquo; &ldquo;we,&rdquo; &ldquo;our&rdquo;) is the data controller for personal information collected through geostrategicstudies.org. Contact: info@geostrategicstudies.org.</p></section>
          <section><h2 className="font-serif text-2xl font-bold text-[#1a1a1a] border-b-2 border-[#1a1a1a] pb-2">2. Information We Collect</h2><p className="mt-4">We collect personal information you voluntarily provide through our forms:</p><ul className="list-disc pl-6 space-y-1 mt-2"><li><strong>Manuscript submissions:</strong> name, email, institution, paper content</li><li><strong>Contact form:</strong> name, email, organisation, message</li><li><strong>Reviewer registration:</strong> name, email, institution, expertise areas, academic profile links</li><li><strong>Editorial board applications:</strong> name, email, institution, CV/profile links, statement of interest</li></ul><p className="mt-3">We do not use cookies for tracking or advertising. We do not use analytics services that collect personally identifiable information.</p></section>
          <section><h2 className="font-serif text-2xl font-bold text-[#1a1a1a] border-b-2 border-[#1a1a1a] pb-2">3. How We Use Your Information</h2><p className="mt-4">We use collected information solely for:</p><ul className="list-disc pl-6 space-y-1 mt-2"><li>Processing and reviewing manuscript submissions</li><li>Responding to contact inquiries</li><li>Managing the peer reviewer pool and matching reviewers to manuscripts</li><li>Processing editorial board applications</li><li>Communicating about journal operations and publication decisions</li></ul><p className="mt-3">We will never sell, rent, or share your personal information with third parties for marketing purposes.</p></section>
          <section><h2 className="font-serif text-2xl font-bold text-[#1a1a1a] border-b-2 border-[#1a1a1a] pb-2">4. Data Storage & Security</h2><p className="mt-4">Personal data is stored in a secured PostgreSQL database hosted by Neon (US East). The website is hosted on Vercel. We implement reasonable technical and organisational measures to protect your data, including encrypted connections (HTTPS) and access controls.</p></section>
          <section><h2 className="font-serif text-2xl font-bold text-[#1a1a1a] border-b-2 border-[#1a1a1a] pb-2">5. Data Retention</h2><p className="mt-4">Manuscript submissions and reviewer registrations are retained indefinitely for the purposes of journal operations and academic record-keeping. Contact form submissions are retained for 2 years. You may request deletion of your personal data at any time by contacting info@geostrategicstudies.org.</p></section>
          <section><h2 className="font-serif text-2xl font-bold text-[#1a1a1a] border-b-2 border-[#1a1a1a] pb-2">6. Your Rights</h2><p className="mt-4">You have the right to: access your personal data; request correction of inaccurate data; request deletion of your data; withdraw consent for processing; and lodge a complaint with a supervisory authority. To exercise these rights, contact info@geostrategicstudies.org.</p></section>
          <section><h2 className="font-serif text-2xl font-bold text-[#1a1a1a] border-b-2 border-[#1a1a1a] pb-2">7. Changes to This Policy</h2><p className="mt-4">We may update this policy from time to time. Changes will be posted on this page with an updated revision date.</p></section>
        </div>
      </div>
      <footer className="bg-[#080d18] text-white/30 py-8 border-t-[3px] border-[#b91c1c]"><div className="max-w-[860px] mx-auto px-8 text-[11px] text-center">&copy; 2026 Geo-Strategic Studies Organisation.</div></footer>
    </div>
  );
}
